name: spectral_rhythm_detector
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- hmmlearn==0.2.2
- numpy
- scipy
- pandas
- seaborn
- scikit-learn
- matplotlib
- spectral_connectivity
- scipy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip
- pip:
  - nb-black
